### ISSUE TITLE
System Update

### ISSUE THREAD

**Issue by 0x-buffer** [Havoc-OS/android_packages_apps_HavocSettings#99]
I recently downloaded the `Havoc-OS-v3.6-20200619-tulip-Official.zip` from sourceforge and after flashing it properly as suggested by the XDA Developers thread doing a clean flash .

I cant find the system update setting. when i search the settings i can see system updates but when i click on that It Takes me about phone and i cant find the update there thats why i am doing a new clean flash again for the new version..

Please do something......

**Comment by anubhavanand1516** [comment]
you are going right way In any custom rom if you wants to update ,you have to download update version of that rom then you have to flash that rom without wap the older version ,after flash you can see that you older version gets updated.

**Comment by 0x-buffer** [comment]
Thanks for letting me know.. But if Havoc is an Official OS then it must have an updater right??. Anyway I'm fine with either a dirty flash or a clean flash.
